columns_to_keep = [
    "re_arabic_world",
    "re_central_europe",
    "re_chinese_world",
    "re_eastern_europe",
    "re_france",
    "re_german_world",
    "re_greek_world",
    "re_indian_world",
    "re_italy",
    "re_japan",
    "re_low_countries",
    "re_nordic_countries",
    "re_persian_world",
    "re_slav_world",
    "re_spain",
    "re_united_kingdom",
    "re_korea",
    "re_south_east_asia",
]

columns_eu_unique = [
    "re_central_europe",
    "re_france",
    "re_german_world",
    "re_greek_world",
    "re_italy",
    "re_low_countries",
    "re_nordic_countries",
    "re_persian_world",
    "re_slav_world",
    "re_spain",
    "re_united_kingdom",
]


columns_non_eu_unique = [
    "re_arabic_world",
    "re_chinese_world",
    "re_indian_world",
    "re_japan",
    "re_persian_world",
    "re_korea",
    "re_south_east_asia",
]


columns_non_eu = [
    "re_arabic_world",
    "re_chinese_world",
    "re_indian_world",
    "re_japan",
    "re_persian_world",
    "re_korea",
    "re_ottoman_turkey",
    "re_arabian_peninsula",
    "re_south_east_asia",
]


columns_eu = [
    "re_austria",
    "re_balkans",
    "re_belgium",
    "re_british_islands",
    "re_central_europe",
    "re_denmark",
    "re_eastern_europe",
    "re_finland",
    "re_france",
    "re_german_world",
    "re_germany",
    "re_greece",
    "re_greek_world",
    "re_iceland",
    "re_ireland",
    "re_italy",
    "re_latin",
    "re_low_countries",
    "re_mediterreanean",
    "re_muslim_world",
    "re_netherlands",
    "re_nordic_countries",
    "re_north_france",
    "re_north_italy",
    "re_northwestern_europe",
    "re_norway",
    "re_portugal",
    "re_slav_world",
    "re_south_france",
    "re_south_italy",
    "re_southwestern_europe",
    "re_spain",
    "re_sweden",
    "re_switzerland",
    "re_united_kingdom",
    "re_western_europe",
]
